<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BanksTableSeeder extends Seeder {

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('banks')->delete();

        DB::table('banks')->insert([
            ['bank_code' => '332', 'title' => 'Acesso Soluções de Pagamento S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '117', 'title' => 'ADVANCED CORRETORA DE CÂMBIO LTDA' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '272', 'title' => 'AGK CORRETORA DE CAMBIO S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '349', 'title' => 'AMAGGI S.A. – CRÉDITO, FINANCIAMENTO E INVESTIMENTO' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '188', 'title' => 'ATIVA INVESTIMENTOS S.A. CORRETORA DE TÍTULOS, CÂMBIO E VALORES' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '280', 'title' => 'Avista S.A. Crédito, Financiamento e Investimento' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '080', 'title' => 'B&T CORRETORA DE CAMBIO LTDA.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '654', 'title' => 'Banco A.J.Renner S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '246', 'title' => 'Banco ABC Brasil S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '075', 'title' => 'Banco ABN AMRO S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '121', 'title' => 'Banco Agibank S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '025', 'title' => 'Banco Alfa S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '065', 'title' => 'Banco Andbank (Brasil) S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '213', 'title' => 'Banco Arbi S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '096', 'title' => 'Banco B3 S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '024', 'title' => 'Banco BANDEPE S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '330', 'title' => 'Banco Bari de Investimentos e Financiamentos S/A' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '318', 'title' => 'Banco BMG S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '752', 'title' => 'Banco BNP Paribas Brasil S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '107', 'title' => 'Banco BOCOM BBM S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '063', 'title' => 'Banco Bradescard S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '036', 'title' => 'Banco Bradesco BBI S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '122', 'title' => 'Banco Bradesco BERJ S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '394', 'title' => 'Banco Bradesco Financiamentos S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '237', 'title' => 'Banco Bradesco S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '218', 'title' => 'Banco BS2 S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '208', 'title' => 'Banco BTG Pactual S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '336', 'title' => 'Banco C6 S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '473', 'title' => 'Banco Caixa Geral – Brasil S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '412', 'title' => 'Banco Capital S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '040', 'title' => 'Banco Cargill S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '739', 'title' => 'Banco Cetelem S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '233', 'title' => 'Banco Cifra S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '745', 'title' => 'Banco Citibank S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '241', 'title' => 'Banco Clássico S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '756', 'title' => 'Banco Cooperativo do Brasil S.A. – BANCOOB' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '748', 'title' => 'Banco Cooperativo Sicredi S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '222', 'title' => 'Banco Credit Agricole Brasil S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '505', 'title' => 'Banco Credit Suisse (Brasil) S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '069', 'title' => 'Banco Crefisa S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '266', 'title' => 'Banco Cédula S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '003', 'title' => 'Banco da Amazônia S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '083', 'title' => 'Banco da China Brasil S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '707', 'title' => 'Banco Daycoval S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '300', 'title' => 'Banco de La Nacion Argentina' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '495', 'title' => 'Banco de La Provincia de Buenos Aires' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '335', 'title' => 'Banco Digio S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '001', 'title' => 'Banco do Brasil S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '047', 'title' => 'Banco do Estado de Sergipe S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '037', 'title' => 'Banco do Estado do Pará S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '041', 'title' => 'Banco do Estado do Rio Grande do Sul S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '004', 'title' => 'Banco do Nordeste do Brasil S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '265', 'title' => 'Banco Fator S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '224', 'title' => 'Banco Fibra S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '626', 'title' => 'Banco Ficsa S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '094', 'title' => 'Banco Finaxis S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '612', 'title' => 'Banco Guanabara S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '012', 'title' => 'Banco Inbursa S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '604', 'title' => 'Banco Industrial do Brasil S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '653', 'title' => 'Banco Indusval S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '077', 'title' => 'Banco Inter S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '249', 'title' => 'Banco Investcred Unibanco S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '479', 'title' => 'Banco ItauBank S.A' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '184', 'title' => 'Banco Itaú BBA S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '029', 'title' => 'Banco Itaú Consignado S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '376', 'title' => 'Banco J. P. Morgan S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '074', 'title' => 'Banco J. Safra S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '217', 'title' => 'Banco John Deere S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '076', 'title' => 'Banco KDB S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '757', 'title' => 'Banco KEB HANA do Brasil S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '600', 'title' => 'Banco Luso Brasileiro S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '389', 'title' => 'Banco Mercantil do Brasil S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '370', 'title' => 'Banco Mizuho do Brasil S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '746', 'title' => 'Banco Modal S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '066', 'title' => 'Banco Morgan Stanley S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '456', 'title' => 'Banco MUFG Brasil S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '243', 'title' => 'Banco Máxima S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '007', 'title' => 'Banco Nacional de Desenvolvimento Econômico e Social – BNDES' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '169', 'title' => 'Banco Olé Bonsucesso Consignado S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '079', 'title' => 'Banco Original do Agronegócio S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '212', 'title' => 'Banco Original S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '712', 'title' => 'Banco Ourinvest S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '623', 'title' => 'Banco PAN S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '611', 'title' => 'Banco Paulista S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '643', 'title' => 'Banco Pine S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '747', 'title' => 'Banco Rabobank International Brasil S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '633', 'title' => 'Banco Rendimento S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '741', 'title' => 'Banco Ribeirão Preto S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '120', 'title' => 'Banco Rodobens S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '422', 'title' => 'Banco Safra S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '033', 'title' => 'Banco Santander (Brasil) S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '743', 'title' => 'Banco Semear S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '754', 'title' => 'Banco Sistema S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '630', 'title' => 'Banco Smartbank S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '366', 'title' => 'Banco Société Générale Brasil S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '637', 'title' => 'Banco Sofisa S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '464', 'title' => 'Banco Sumitomo Mitsui Brasileiro S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '082', 'title' => 'Banco Topázio S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '018', 'title' => 'Banco Tricury S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '634', 'title' => 'Banco Triângulo S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '655', 'title' => 'Banco Votorantim S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '610', 'title' => 'Banco VR S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '119', 'title' => 'Banco Western Union do Brasil S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '124', 'title' => 'Banco Woori Bank do Brasil S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '348', 'title' => 'Banco XP S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '081', 'title' => 'BancoSeguro S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '021', 'title' => 'BANESTES S.A. Banco do Estado do Espírito Santo' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '755', 'title' => 'Bank of America Merrill Lynch Banco Múltiplo S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '268', 'title' => 'BARI COMPANHIA HIPOTECÁRIA' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '250', 'title' => 'BCV – Banco de Crédito e Varejo S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '144', 'title' => 'BEXS Banco de Câmbio S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '253', 'title' => 'Bexs Corretora de Câmbio S/A' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '134', 'title' => 'BGC LIQUIDEZ DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '017', 'title' => 'BNY Mellon Banco S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '301', 'title' => 'BPP Instituição de Pagamento S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '126', 'title' => 'BR Partners Banco de Investimento S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '070', 'title' => 'BRB – Banco de Brasília S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '092', 'title' => 'Brickell S.A. Crédito' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '173', 'title' => 'BRL Trust Distribuidora de Títulos e Valores Mobiliários S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '142', 'title' => 'Broker Brasil Corretora de Câmbio Ltda.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '292', 'title' => 'BS2 Distribuidora de Títulos e Valores Mobiliários S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '104', 'title' => 'Caixa Econômica Federal' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '309', 'title' => 'CAMBIONET CORRETORA DE CÂMBIO LTDA.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '288', 'title' => 'CAROL DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LTDA.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '130', 'title' => 'CARUANA S.A. – SOCIEDADE DE CRÉDITO, FINANCIAMENTO E INVESTIMENTO' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '159', 'title' => 'Casa do Crédito S.A. Sociedade de Crédito ao Microempreendedor' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '114', 'title' => 'Central Cooperativa de Crédito no Estado do Espírito Santo – CECOOP' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '091', 'title' => 'CENTRAL DE COOPERATIVAS DE ECONOMIA E CRÉDITO MÚTUO DO ESTADO DO RIO GRANDE DO S' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '320', 'title' => 'China Construction Bank (Brasil) Banco Múltiplo S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '477', 'title' => 'Citibank N.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '180', 'title' => 'CM CAPITAL MARKETS CORRETORA DE CÂMBIO, TÍTULOS E VALORES MOBILIÁRIOS LTDA' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '127', 'title' => 'Codepe Corretora de Valores e Câmbio S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '163', 'title' => 'Commerzbank Brasil S.A. – Banco Múltiplo' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '133', 'title' => 'CONFEDERAÇÃO NACIONAL DAS COOPERATIVAS CENTRAIS DE CRÉDITO E ECONOMIA FAMILIAR E' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '136', 'title' => 'CONFEDERAÇÃO NACIONAL DAS COOPERATIVAS CENTRAIS UNICRED LTDA. – UNICRED DO BRASI' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '060', 'title' => 'Confidence Corretora de Câmbio S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '097', 'title' => 'Cooperativa Central de Crédito Noroeste Brasileiro Ltda.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '085', 'title' => 'Cooperativa Central de Crédito – AILOS' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '279', 'title' => 'COOPERATIVA DE CREDITO RURAL DE PRIMAVERA DO LESTE' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '016', 'title' => 'COOPERATIVA DE CRÉDITO MÚTUO DOS DESPACHANTES DE TRÂNSITO DE SANTA CATARINA E RI' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '281', 'title' => 'Cooperativa de Crédito Rural Coopavel' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '322', 'title' => 'Cooperativa de Crédito Rural de Abelardo Luz – Sulcredi/Crediluz' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '286', 'title' => 'COOPERATIVA DE CRÉDITO RURAL DE OURO SULCREDI/OURO' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '273', 'title' => 'Cooperativa de Crédito Rural de São Miguel do Oeste – Sulcredi/São Miguel' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '098', 'title' => 'Credialiança Cooperativa de Crédito Rural' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '010', 'title' => 'CREDICOAMO CREDITO RURAL COOPERATIVA' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '089', 'title' => 'CREDISAN COOPERATIVA DE CRÉDITO' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '011', 'title' => 'CREDIT SUISSE HEDGING-GRIFFO CORRETORA DE VALORES S.A' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '342', 'title' => 'Creditas Sociedade de Crédito Direto S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '321', 'title' => 'CREFAZ SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E A EMPRESA DE PEQUENO PORTE LT' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '289', 'title' => 'DECYSEO CORRETORA DE CAMBIO LTDA.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '487', 'title' => 'Deutsche Bank S.A. – Banco Alemão' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '140', 'title' => 'Easynvest – Título Corretora de Valores SA' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '149', 'title' => 'Facta Financeira S.A. – Crédito Financiamento e Investimento' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '196', 'title' => 'FAIR CORRETORA DE CAMBIO S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '343', 'title' => 'FFA SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE LTDA.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '331', 'title' => 'Fram Capital Distribuidora de Títulos e Valores Mobiliários S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '285', 'title' => 'Frente Corretora de Câmbio Ltda.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '278', 'title' => 'Genial Investimentos Corretora de Valores Mobiliários S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '364', 'title' => 'GERENCIANET PAGAMENTOS DO BRASIL LTDA' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '138', 'title' => 'Get Money Corretora de Câmbio S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '064', 'title' => 'Goldman Sachs do Brasil Banco Múltiplo S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '177', 'title' => 'Guide Investimentos S.A. Corretora de Valores' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '146', 'title' => 'GUITTA CORRETORA DE CAMBIO LTDA.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '078', 'title' => 'Haitong Banco de Investimento do Brasil S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '062', 'title' => 'Hipercard Banco Múltiplo S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '189', 'title' => 'HS FINANCEIRA S/A CREDITO, FINANCIAMENTO E INVESTIMENTOS' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '269', 'title' => 'HSBC Brasil S.A. – Banco de Investimento' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '271', 'title' => 'IB Corretora de Câmbio, Títulos e Valores Mobiliários S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '157', 'title' => 'ICAP do Brasil Corretora de Títulos e Valores Mobiliários Ltda.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '132', 'title' => 'ICBC do Brasil Banco Múltiplo S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '492', 'title' => 'ING Bank N.V.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '139', 'title' => 'Intesa Sanpaolo Brasil S.A. – Banco Múltiplo' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '652', 'title' => 'Itaú Unibanco Holding S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '341', 'title' => 'Itaú Unibanco S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '488', 'title' => 'JPMorgan Chase Bank' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '399', 'title' => 'Kirton Bank S.A. – Banco Múltiplo' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '293', 'title' => 'Lastro RDV Distribuidora de Títulos e Valores Mobiliários Ltda.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '105', 'title' => 'Lecca Crédito, Financiamento e Investimento S/A' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '145', 'title' => 'LEVYCAM – CORRETORA DE CAMBIO E VALORES LTDA.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '113', 'title' => 'Magliano S.A. Corretora de Cambio e Valores Mobiliarios' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '323', 'title' => 'MERCADOPAGO.COM REPRESENTACOES LTDA.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '274', 'title' => 'MONEY PLUS SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E A EMPRESA DE PEQUENO PORT' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '259', 'title' => 'MONEYCORP BANCO DE CÂMBIO S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '128', 'title' => 'MS Bank S.A. Banco de Câmbio' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '354', 'title' => 'NECTON INVESTIMENTOS S.A. CORRETORA DE VALORES MOBILIÁRIOS E COMMODITIES' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '191', 'title' => 'Nova Futura Corretora de Títulos e Valores Mobiliários Ltda.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '753', 'title' => 'Novo Banco Continental S.A. – Banco Múltiplo' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '260', 'title' => 'Nu Pagamentos S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '111', 'title' => 'OLIVEIRA TRUST DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIARIOS S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '319', 'title' => 'OM DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '613', 'title' => 'Omni Banco S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '290', 'title' => 'Pagseguro Internet S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '254', 'title' => 'Paraná Banco S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '326', 'title' => 'PARATI – CREDITO, FINANCIAMENTO E INVESTIMENTO S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '194', 'title' => 'PARMETAL DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '174', 'title' => 'PERNAMBUCANAS FINANCIADORA S.A. – CRÉDITO, FINANCIAMENTO E INVESTIMENTO' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '315', 'title' => 'PI Distribuidora de Títulos e Valores Mobiliários S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '100', 'title' => 'Planner Corretora de Valores S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '125', 'title' => 'Plural S.A. – Banco Múltiplo' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '108', 'title' => 'PORTOCRED S.A. – CREDITO, FINANCIAMENTO E INVESTIMENTO' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '306', 'title' => 'PORTOPAR DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LTDA.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '093', 'title' => 'PÓLOCRED SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORT' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '329', 'title' => 'QI Sociedade de Crédito Direto S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '283', 'title' => 'RB CAPITAL INVESTIMENTOS DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LIMITADA' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '101', 'title' => 'RENASCENCA DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '270', 'title' => 'Sagitur Corretora de Câmbio Ltda.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '751', 'title' => 'Scotiabank Brasil S.A. Banco Múltiplo' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '276', 'title' => 'Senff S.A. – Crédito, Financiamento e Investimento' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '545', 'title' => 'SENSO CORRETORA DE CAMBIO E VALORES MOBILIARIOS S.A' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '190', 'title' => 'SERVICOOP – COOPERATIVA DE CRÉDITO DOS SERVIDORES PÚBLICOS ESTADUAIS DO RIO GRAN' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '183', 'title' => 'SOCRED S.A. – SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO P' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '365', 'title' => 'SOLIDUS S.A. CORRETORA DE CAMBIO E VALORES MOBILIARIOS' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '299', 'title' => 'SOROCRED CRÉDITO, FINANCIAMENTO E INVESTIMENTO S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '014', 'title' => 'State Street Brasil S.A. – Banco Comercial' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '197', 'title' => 'Stone Pagamentos S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '340', 'title' => 'Super Pagamentos e Administração de Meios Eletrônicos S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '307', 'title' => 'Terra Investimentos Distribuidora de Títulos e Valores Mobiliários Ltda.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '352', 'title' => 'TORO CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '095', 'title' => 'Travelex Banco de Câmbio S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '143', 'title' => 'Treviso Corretora de Câmbio S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '131', 'title' => 'TULLETT PREBON BRASIL CORRETORA DE VALORES E CÂMBIO LTDA' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '129', 'title' => 'UBS Brasil Banco de Investimento S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '015', 'title' => 'UBS Brasil Corretora de Câmbio, Títulos e Valores Mobiliários S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '099', 'title' => 'UNIPRIME CENTRAL – CENTRAL INTERESTADUAL DE COOPERATIVAS DE CREDITO LTDA.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '084', 'title' => 'Uniprime Norte do Paraná – Coop de Economia e Crédito Mútuo dos Médicos' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '373', 'title' => 'UP.P SOCIEDADE DE EMPRÉSTIMO ENTRE PESSOAS S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '298', 'title' => 'Vip’s Corretora de Câmbio Ltda.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '296', 'title' => 'VISION S.A. CORRETORA DE CAMBIO' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '367', 'title' => 'VITREO DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '310', 'title' => 'VORTX DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LTDA.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '102', 'title' => 'XP INVESTIMENTOS CORRETORA DE CÂMBIO,TÍTULOS E VALORES MOBILIÁRIOS S/A' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '325', 'title' => 'Órama Distribuidora de Títulos e Valores Mobiliários S.A.' , 'cnab400' => false, 'cnab240' => false],
            ['bank_code' => '355', 'title' => 'ÓTIMO SOCIEDADE DE CRÉDITO DIRETO S.A.' , 'cnab400' => false, 'cnab240' => false],
        ]);
    }

}
