stages:
  - testing
  - develop
  - staging
variables:
  GIT_STRATEGY: clone
deploy_develop:
  environment: testing
  stage: testing
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )' 
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 777 ~/.ssh
    - ssh-keyscan $EC2_IPADDRESS >> ~/.ssh/known_hosts
    - chmod 777 ~/.ssh/known_hosts
    
  script:
    - ssh admin@$EC2_IPADDRESS "sudo -i cd /var/www/html/rentalcars-api"
    - git reset --hard HEAD
    - git checkout testing
    - git pull origin testing 
    - composer i
    
  tags:
    - financ-homolog
  only:
    - testing
#deploy_master:
#  stage: deploy
#  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
#  script:
#    - aws s3 cp s3://123-deploy/financeiro-art.pem /tmp/financeiro-art.pem
#    - aws s3 cp s3://123-deploy/autoscaling-deploy.sh /tmp/autoscaling-deploy.sh
#    - chmod 0400 /tmp/financeiro-art.pem
#   - chmod 755 /tmp/autoscaling-deploy.sh
#    - bash /tmp/autoscaling-deploy.sh ASG-123 main /tmp/financeiro-art.pem 0 80 /home/admin/api
#  only:
#    - mai
