stages:
  - testing
  - develop
  - staging
variables:
  GIT_STRATEGY: clone
deploy_develop:
  environment: testing
  stage: testing
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  before_script:
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    
  script:
    - ssh -o StrictHostKeyChecking=no admin@$EC2_IPADDRESS "hostname && cd /var/www/html/dev-api/api && sudo git reset --hard HEAD && sudo git checkout testing && sudo git pull origin testing"
    
    # - "cd /var/www/html/rentalcars-api/"
    #- "dir"
    #- "pwd"
    #- git reset --hard HEAD
    #- git checkout -b testing
    #- git pull origin testing
    
    
  tags:
    - financ-homolog
  only:
    - testing
#deploy_master
#  stage: deploy
#  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
#  script:
#    - aws s3 cp s3://123-deploy/financeiro-art.pem /tmp/financeiro-art.pem
#    - aws s3 cp s3://123-deploy/autoscaling-deploy.sh /tmp/autoscaling-deploy.sh
#    - chmod 0400 /tmp/financeiro-art.pem
#   - chmod 755 /tmp/autoscaling-deploy.sh
#    - bash /tmp/autoscaling-deploy.sh ASG-123 main /tmp/financeiro-art.pem 0 80 /home/admin/api
#  only:
#    - mai
