stages:
  - deploy
variables:
  GIT_STRATEGY: clone
deploy_master:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - aws s3 cp s3://back-financ-s3/financeiro-art.pem /tmp/financeiro-art.pem
    - aws s3 cp s3://back-financ-s3y/autoscaling-deploy.sh /tmp/autoscaling-deploy.sh
    - chmod 0400 /tmp/financeiro-art.pem
    - chmod 755 /tmp/autoscaling-deploy.sh
    - bash /tmp/autoscaling-deploy.sh finac-ASG main /tmp/financeiro-art.pem 0 80 /home/admin/api
  only:
    - develop
#
